server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: energy-market-service
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"
      allow-credentials: true

# WebSocket configuration
websocket:
  endpoint: /ws
  topic:
    energy-prices: /topic/energy-prices
    market-stats: /topic/market-stats
    
# Energy market simulation settings
energy-market:
  simulation:
    update-interval-ms: 1000
    price-volatility: 0.05
    base-prices:
      electricity: 50.0
      gas: 30.0
      coal: 40.0
      solar: 20.0
      wind: 25.0
      nuclear: 35.0
      hydro: 22.0

logging:
  level:
    com.energymarket: DEBUG
    org.springframework.web: INFO
    org.springframework.websocket: DEBUG