name: Build

on: 
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          
      # Backend - compile and test
      - name: Backend Build
        run: |
          cd backend
          mvn compile
          
      - name: Backend Test
        run: |
          cd backend
          # Start server in background
          java -cp target/classes com.energymarket.EnergyMarketService &
          SERVER_PID=$!
          
          # Wait for server to be ready
          echo "Waiting for server to start..."
          for i in {1..30}; do
            if curl -f http://localhost:8080/api/energy >/dev/null 2>&1; then
              echo "Server is ready!"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "Server failed to start"
              kill $SERVER_PID 2>/dev/null || true
              exit 1
            fi
            sleep 1
          done
          
          # Test the API
          curl -f http://localhost:8080/api/energy || exit 1
          
          # Clean up
          kill $SERVER_PID
          
      # Frontend - build with pnpm
      - name: Frontend Build
        run: |
          cd frontend
          pnpm install
          pnpm run build
          
          # Check build output exists
          [ -d dist ] || exit 1
          
          # Check build size is reasonable (under 1MB)
          size=$(du -sb dist | cut -f1)
          echo "Build size: $size bytes"
          if [ $size -gt 1048576 ]; then
            echo "Build too large!"
            exit 1
          fi 