name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Build Backend
        run: cd backend && mvn compile
      
      - name: Build Frontend  
        run: cd frontend && npm install && npm run build 